services:
  - type: web
    name: sql-crawler-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
